name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature you'd like to see added.
      placeholder: What would you like to add?
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve. Is it related to a current limitation?
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you'd like to implement.
      placeholder: How should this be implemented?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches or solutions?
      placeholder: What other options exist?
    validations:
      required: false

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe how this feature would be used and the benefits it would provide.
      placeholder: How would users benefit from this?
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references that might be helpful.
      placeholder: Anything else we should know?
    validations:
      required: false
